name: CD

on:
  push:
    branches:
      - master
    paths:
      - 'bot/**'
      - 'smp-client/**'
      - '.github/workflows/CD.yml'
      - 'docker-compose.yml'
  workflow_dispatch:

concurrency:
  group: "CD"
  cancel-in-progress: true

jobs:
  build:
    uses: ed-asriyan/remote-docker-compose-deploy/.github/workflows/build.yml@v1
    with:
      compose-file: docker-compose.yml

  deploy:
    needs: build
    uses: ed-asriyan/remote-docker-compose-deploy/.github/workflows/deploy.yml@v1
    with:
      compose-file: docker-compose.yml
    secrets: inherit
